protected/models/Bookings.php
<?php

/**
 * This is the model class for table "pb_bookings".
 *
 * The followings are the available columns in table 'pb_bookings':
 * @property string $id
 * @property string $booked_user_id
 * @property string $users_name
 * @property string $username
 * @property string $edited_user_id
 * @property string $time_created
 * @property string $time_edited
 * @property string $slot_booked
 * @property integer $slot_locked
 * @property integer $slot_disabled
 */
class Bookings extends CActiveRecord
{
	const LOCKED_NO = 0;
	const LOCKED_YES = 1;
	const DISABLED_NO = 0;
	const DISABLED_YES = 1;
	
	public $blockBookingValues = array(
		1=>'1',
		2=>'2',
		3=>'3',
		4=>'4',
		5=>'5',
		6=>'6',
		7=>'7',
		8=>'8',
		9=>'9',
		10=>'10',
		11=>'11',
		12=>'12',
		13=>'13',
		14=>'14',
		15=>'15',
		16=>'16',
		17=>'17',
		18=>'18',
		19=>'19',
		20=>'20',
		21=>'21',
		22=>'22',
		23=>'23',
		24=>'24'
	);
	
	public $bookingDayTitles = array(
		1=>'Sunday',
		2=>'Monday',
		3=>'Tuesday',
		4=>'Wednesday',
		5=>'Thursday',
		6=>'Friday',
		7=>'Saturday'
	);
	
	public $bookingRowTitles = array(
		'Time',
		'00:00',
		'01:00',
		'02:00',
		'03:00',
		'04:00',
		'05:00',
		'06:00',
		'07:00',
		'08:00',
		'09:00',
		'10:00',
		'11:00',
		'12:00',
		'13:00',
		'14:00',
		'15:00',
		'16:00',
		'17:00',
		'18:00',
		'19:00',
		'20:00',
		'21:00',
		'22:00',
		'23:00',
		'Time'
	);
	
	/**
	 * Returns the static model of the specified AR class.
	 * @param string $className active record class name.
	 * @return Bookings the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'pb_bookings';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('users_name, username, time_created, slot_booked', 'required'),
			array('username', 'email'),
			array('booked_user_id, slot_locked, slot_disabled', 'numerical', 'integerOnly'=>true),
			array('booked_user_id, edited_user_id', 'length', 'max'=>10),
			array('users_name', 'length', 'max'=>64),
			array('username', 'length', 'max'=>128),
			array('time_edited', 'safe'),
			// The following rule is used by search().
			// Please remove those attributes that should not be searched.
			array('id, booked_user_id, users_name, username, edited_user_id, time_created, time_edited, slot_booked, slot_locked, slot_disabled', 'safe', 'on'=>'search'),
			
			array('users_name','filter','filter'=>array($obj=new CHtmlPurifier(),'purify')),
			array('username','filter','filter'=>array($obj=new CHtmlPurifier(),'purify')),
			array('slot_booked','filter','filter'=>array($obj=new CHtmlPurifier(),'purify')),
			array('slot_locked','filter','filter'=>array($obj=new CHtmlPurifier(),'purify')),
			array('slot_disabled','filter','filter'=>array($obj=new CHtmlPurifier(),'purify')),
			
			/*array('users_name','filter','filter'=>function($v){ return strip_tags($v);}),
			array('username','filter','filter'=>function($v){ return strip_tags($v);}),
			array('slot_booked','filter','filter'=>function($v){ return strip_tags($v);}),
			array('slot_locked','filter','filter'=>function($v){ return strip_tags($v);}),
			array('slot_disabled','filter','filter'=>function($v){ return strip_tags($v);}),*/
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array();
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'ID',
			'booked_user_id' => 'Booked User',
			'users_name' => 'Name',
			'username' => 'Email',
			'edited_user_id' => 'Edited User',
			'time_created' => 'Time Created',
			'time_edited' => 'Time Edited',
			'slot_booked' => 'Desired Prayer Slot',
			'slot_locked' => 'Private Prayer Slot',
			'slot_disabled' => 'Disable this Prayer Slot',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 * @return CActiveDataProvider the data provider that can return the models based on the search/filter conditions.
	 */
	public function search()
	{
		// Warning: Please modify the following code to remove attributes that
		// should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('id',$this->id,true);
		$criteria->compare('booked_user_id',$this->booked_user_id,true);
		$criteria->compare('users_name',$this->users_name,true);
		$criteria->compare('username',$this->username,true);
		$criteria->compare('edited_user_id',$this->edited_user_id,true);
		$criteria->compare('time_created',$this->time_created,true);
		$criteria->compare('time_edited',$this->time_edited,true);
		$criteria->compare('slot_booked',$this->slot_booked,true);
		$criteria->compare('slot_locked',$this->slot_locked);
		$criteria->compare('slot_disabled',$this->slot_disabled);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}
	
    public function scopes() {
        return array(
            'published'=>array(
                'condition'=>'status=1',
            ),
            'recently'=>array(
                'order'=>'create_time DESC',
                'limit'=>5,
            ),
        );
    }
	
	//*********** Custom Functions ***********//
	
	/**
	 * Prepares time_created, create_user_id, time_edited and update_user_id attributes before performing validation.
	 */
	protected function beforeValidate() {
		if($this->isNewRecord) {
			// set the create date, last updated date and the user doing the creating
			$this->time_created = $this->time_edited = new CDbExpression( 'NOW()' );
			$this->booked_user_id = $this->edited_user_id = Yii::app()->user->id;
		} else {
			//not a new record, so just set the last updated time and last updated user id
			$this->time_edited = new CDbExpression( 'NOW()' );
			$this->edited_user_id = Yii::app()->user->id;
       }
       return parent::beforeValidate();
	}
	
	/**
	 * @return array the block booking possible values
	 */
	public function getBlockBookingValues() {
		return $this->blockBookingValues;
	}
	
	/**
	 * @return array the locked options for the form drop down
	 */
	public function getLockedOptions() {
		return array(
			self::LOCKED_NO => 'No',
			self::LOCKED_YES => 'Yes',
		); 
	}
	
	/**
	 * @return array the disabled options for the form drop down
	 */
	public function getDisabledOptions() {
		return array(
			self::DISABLED_NO => 'No',
			self::DISABLED_YES => 'Yes',
		); 
	}
	
	/**
	 * @return string the locked text display for the booking view
	 */
	public function getLockedText() {
		$lockedOptions=$this->lockedOptions;
		return isset($lockedOptions[$this->slot_locked]) ?
			$lockedOptions[$this->slot_locked] : "unknown status ({$this->slot_locked})";
	}
	
	/**
	 * @return string the disabled text display for the booking view
	 */
     public function getDisabledText() {
		$disabledOptions=$this->disabledOptions;
		return isset($disabledOptions[$this->slot_disabled]) ?
			$disabledOptions[$this->slot_disabled] : "unknown type ({$this->slot_disabled})";
	}
	
	/**
	 * @return array the planner column titles
	 */
	public function getColumnTitles() {
		return $this->bookingDayTitles;
	}
	
	/**
	 * @return array the planner row titles
	 */
	public function gettRowTitles() {
		return $this->bookingRowTitles; 
	}
}

protected/controllers/BookingsController.php
<?php

class BookingsController extends Controller
{
	//const _timeWeekStarts = 'Sunday';	// The Calendar starts on day
	const TIME_DAYS_OFFSET = 4;			// Time offset to have the week begin on Sunday. Timestamp starts on a Wednesday
	//const _timeZone = 'Europe/London';	// Not currently used
	
	private $bookings_week_id = 1;
	private $parsed_booking_entries = array();
	
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * Declares class-based actions.
	 */
	public function actions()
	{
		return array(
			// captcha action renders the CAPTCHA image displayed on the contact page
			'captcha'=>array(
				'class'=>'CCaptchaAction',
				'backColor'=>0xFFFFFF,
			),
		);
	}
	
	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		$userModel=new User;
		
		return array(
			array(
				'allow',  // allow all users to perform 'index' and 'view' actions
                'actions'=>array('create','planner'),
                'users'=>array('*'),
			),
			array(
				'allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('admin','update','delete','index','view'),
            	'users'=>$userModel->getAdminUsers(),
        	),
			array(
				'deny',  // deny all users
            	'users'=>array('*'),
			), 
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{	
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$invalid_flag = false;
		if ( (isset($_GET['wid'])) && (isset($_GET['hid'])) ) {
			if (is_numeric($_GET['wid'])) {
				$wid = intval($_GET['wid']);
			} else {
				$invalid_flag = true;
			}
		
			if (is_numeric($_GET['hid'])) {
				$hid = intval($_GET['hid']);
			} else {
				$invalid_flag = true;
			}
		} else {
			$invalid_flag = true;
		}
		if ($invalid_flag) throw new CHttpException(400,'Invalid request. Please do not repeat this request again.');
		
		$dataProvider=new CActiveDataProvider(
			'Bookings',
			array(
				'criteria'=>array(
        			'condition'=>'slot_booked=:specifieddattime',
        			'order'=>'id DESC',
        			'params'=>array(
						':specifieddattime'=>$this->getSQLDateFromWIDandDID($wid, $hid),
					),
    			),
    			'pagination'=>array(
        			'pageSize'=>10,
    			),
    		)
		);
	
		$model=new Bookings;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);
		
		$consecutive_hours_to_book = Yii::app()->request->getParam('block_booking', 1);
		
		if(isset($_POST['Bookings'])) {
			
			for($i=0;$i<$consecutive_hours_to_book;$i++) {
				$model=new Bookings;
				$_POST['Bookings']['slot_booked'] = $this->getSQLDateFromWIDandDID($wid,$hid + $i);
				$model->attributes=$_POST['Bookings'];
				$saved_flag = $model->save();
			}
			
			if($saved_flag) {
				if (Yii::app()->request->isAjaxRequest) {
                    echo CJSON::encode(array(
                        'status'=>'success', 
                        'div'=>'<div class="alert alert-success">
									<strong>Booking Successful</strong>
								</div>',
                        ));
                    exit;               
                } else $this->redirect(array('bookings/planner', 'wid'=>$wid));
			}
		}

		if (Yii::app()->request->isAjaxRequest) {
            echo CJSON::encode(array(
                'status'=>'failure', 
                'div'=>$this->renderPartial(
                	'_form',
                	array(
                		'model'=>$model,
						'dataProvider'=>$dataProvider,
						'wid'=>$wid,
						'hid'=>$hid,
                	),
                	true
                )
            ));
            exit;               
        } else $this->render('create',array(
			'model'=>$model,
			'dataProvider'=>$dataProvider,
			'wid'=>$wid,
			'hid'=>$hid,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Bookings']))
		{
			$model->attributes=$_POST['Bookings'];
			if($model->save())
				$this->redirect(array('planner'));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{

        $this->loadModel($id)->delete();

        // if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
        if(!isset($_GET['ajax']))
            $this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('Bookings');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Bookings('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Bookings']))
			$model->attributes=$_GET['Bookings'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer the ID of the model to be loaded
	 */
	public function loadModel($id)
	{
		$model=Bookings::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param CModel the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='bookings-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
	
	/********* Custom Functions *********/
	
	/**
	 * Displays a particular model.
	 */
	public function actionPlanner() {
		//$this->$layout='//layouts/column1';
		
		// Setup a new bookings model
		$model=new Bookings;
		$userModel=new User;
	
		// Generate The current timestamp
		$_currentTimestamp = time();
		
		// Identified the specified week
		if( isset($_GET['wid']) && (is_numeric($_GET['wid'])) ) {
			// Store the specified week
			$this->bookings_week_id = intval($_GET['wid']);
		} else {
			// Find the current week number
			$this->bookings_week_id = floor( ($_currentTimestamp + (self::TIME_DAYS_OFFSET * 60 * 60 * 24)) / (60 * 60 * 24 * 7) ) - 1;
		}
		
		$this->parseBookingEntriesForThisWeek();
		
		// Render the page
		$this->render(
			'planner', 
			array(
				'currentStamp'=>$_currentTimestamp,
				'plannerColumnTitle'=>$model->getColumnTitles(),
				'plannerRowTitle'=>$model->gettRowTitles(),
				'specifiedWeek'=>$this->bookings_week_id,
				'specifiedWeekReadableDate'=>$this->getWeekReadableDateRange($this->bookings_week_id),
				'parseBookingEntriesForThisWeek'=>$this->parsed_booking_entries,
				'isAdminUser'=>$userModel->isAdminUser(Yii::app()->user->id),
			)
		);
	}
	
	/** 
	 * Generate the link to navigate to the next week.
	 */
	public function getNextWeekLink() {
		return $this->bookings_week_id + 1;
	}
	
	/**
	 * Generate the link to navigate to the previous week.
	 */
	public function getPreviousWeekLink() {
		return $this->bookings_week_id - 1;
	}
	
	/**
	 * Generate the readable week label of the date range.
	 */
	public function getWeekReadableDateRange() {
		$fromDate = date( 'l, jS F Y', mktime(0,0,0,1,(($this->bookings_week_id * 7) + self::TIME_DAYS_OFFSET),1970) );
		$toDate = date( 'l, jS F Y', mktime(0,0,0,1,((($this->bookings_week_id * 7) + 6) + self::TIME_DAYS_OFFSET),1970) );
		return $fromDate . ' to ' . $toDate;
	}
	
	/**
	 * Generate the readable date of the targeted day.
	 * @param integer $did the ID of the day to be targeted
	 */
	public function getDayReadableDateInfo($did) {
		return date( 'jS F', mktime(0,0,0,1,((($this->bookings_week_id * 7) + $did ) + self::TIME_DAYS_OFFSET),1970) );
	}
	
	/**
	 * Generate the readable date from the week id and the hour id.
	 * @param integer $wid the ID of the targeted week
	 * @param integer $hid the ID of the targeted hour
	 */
	public function getReadableDateFromWIDandDID($wid, $hid) {
		return date( 'g:ia l, jS F Y', mktime($hid,0,0,1,($wid * 7) + self::TIME_DAYS_OFFSET,1970));
	}
	
	/**
	 * Generate the MySQL date from the week id and the hour id.
	 * @param integer $wid the ID of the targeted week
	 * @param integer $hid the ID of the targeted hour
	 */
	public function getSQLDateFromWIDandDID($wid, $hid) {
		return date( 'Y-m-d H:00:00', mktime($hid,0,0,1,($wid * 7) + self::TIME_DAYS_OFFSET,1970));
	}
	
	/**
	 * Generate the timestamp from the week id and the hour id.
	 * @param integer $wid the ID of the targeted week
	 * @param integer $hid the ID of the targeted hour
	 * @return integer timestamp
	 */
	public function getTimetampFromWIDandDID($wid, $hid) {
		return mktime($hid,0,0,1,($wid * 7) + self::TIME_DAYS_OFFSET,1970);
	}
	
	public function getHourNumberFromHourAndDayID( $hour, $day ) {
		$hour_number = ($hour - 1) + (($day - 1) * 24);
		return $hour_number;
	}
	
	/**

protected/views/bookings/_form.php
<div class="form">

<?php 
	$form = $this->beginWidget('bootstrap.widgets.BootActiveForm', array(
    	'id'=>'bookings-form',
    	'type'=>'inline',
    	'enableClientValidation'=>true,
    	'clientOptions'=>array(
			'validateOnSubmit'=>true,
		),
    	'htmlOptions'=>array('class'=>'well'),
	));
	
	$userModel=new User;
	$userRecord=$userModel->findByPk(Yii::app()->user->id);
	$nameTextField = (isset($userRecord->name)) ? $userRecord->name : '';
	$emailTextField = (isset($userRecord->username)) ? $userRecord->username : '';
?>

<?php 
	if ($model->isNewRecord)
		echo '<p class="note">Book the slot '.$this->getReadableDateFromWIDandDID($wid,$hid).'</p>';
?>

<?php echo $form->errorSummary($model); ?>

<?php 
	if ($model->isNewRecord)
		echo $form->hiddenField($model,'slot_booked',array('value'=>$this->getSQLDateFromWIDandDID($wid,$hid)));
?>

<!-- <div class="row"> -->
	<?php //echo $form->labelEx($model,'booked_user_id'); ?>
	<?php //echo $form->textField($model,'booked_user_id',array('size'=>10,'maxlength'=>10)); ?>
	<?php //echo $form->error($model,'booked_user_id'); ?>
<!-- </div> -->

<?php 
		if ($model->isNewRecord) {
			$output = '';
			$output .= '<div class="control-group">';
			$output .= '<label class="control-label" for="inputIcon">'. $form->labelEx($model,'users_name') .'</label>';
			$output .= '<div class="controls">';
			$output .= $form->textFieldRow($model, 'users_name', array('value'=>CHtml::encode($nameTextField),'class'=>'span10','maxlength'=>64));
			$output .= '<span class="field-error"><strong>'.$form->error($model,'users_name').'</strong></span>';
			$output .= '</div>';
			$output .= '</div>';
			echo $output;
		} else {
			$output = '';
			$output .= '<div class="control-group">';
			$output .= '<label class="control-label" for="inputIcon">'. $form->labelEx($model,'users_name') .'</label>';
			$output .= '<div class="controls">';
			$output .= $form->textFieldRow($model, 'users_name', array('class'=>'span10','maxlength'=>64));
			$output .= '<span class="field-error"><strong>'.$form->error($model,'users_name').'</strong></span>';
			$output .= '</div>';
			$output .= '</div>';
			echo $output;
		}
	?>

<?php 
		if ($model->isNewRecord) {
			$output = '';
			$output .= '<div class="control-group">';
			$output .= '<label class="control-label" for="inputIcon">'. $form->labelEx($model,'username') .'</label>';
			$output .= '<div class="controls">';
			$output .= $form->textFieldRow($model, 'username', array('value'=>CHtml::encode($emailTextField),'class'=>'span10','maxlength'=>128));
			$output .= '<span class="field-error"><strong>'.$form->error($model,'username').'</strong></span>';
			$output .= '</div>';
			$output .= '</div>';
			echo $output;
		} else {
			$output = '';
			$output .= '<div class="control-group">';
			$output .= '<label class="control-label" for="inputIcon">'. $form->labelEx($model,'username') .'</label>';
			$output .= '<div class="controls">';
			$output .= $form->textFieldRow($model, 'username', array('class'=>'span10','maxlength'=>128));
			$output .= '<span class="field-error"><strong>'.$form->error($model,'username').'</strong></span>';
			$output .= '</div>';
			$output .= '</div>';
			echo $output;
		}
	?>

<!-- <div class="row"> -->
	<?php // echo $form->labelEx($model,'edited_user_id'); ?>
	<?php // echo $form->textField($model,'edited_user_id',array('size'=>10,'maxlength'=>10)); ?>
	<?php // echo $form->error($model,'edited_user_id'); ?>
<!-- </div> -->

<!-- <div class="row"> -->
	<?php // echo $form->labelEx($model,'time_created'); ?>
	<?php // echo $form->textField($model,'time_created'); ?>
	<?php // echo $form->error($model,'time_created'); ?>
<!-- </div> -->

<!-- <div class="row"> -->
	<?php // echo $form->labelEx($model,'time_edited'); ?>
	<?php // echo $form->textField($model,'time_edited'); ?>
	<?php // echo $form->error($model,'time_edited'); ?>
<!-- </div> -->

	<?php //echo $form->labelEx($model,'slot_locked'); ?>
	<?php //echo $form->dropDownList($model,'slot_locked',$model->getLockedOptions()); ?>
	<?php //echo $form->error($model,'slot_locked'); ?>
<?php
	$output = '';	
	$output .= '<div class="control-group">';
	$output .= '<label class="control-label" for="inputIcon">'. $form->labelEx($model,'slot_locked') .'</label>';
	$output .= '<div class="controls">';
	$output .= $form->dropDownList($model,'slot_locked',$model->getLockedOptions());
	$output .= '<span class="field-error"><strong>'.$form->error($model,'slot_locked').'</strong></span>';
	$output .= '</div>';
	$output .= '</div>';
	echo $output;
?>
	
<?php
	$output = '';
	if (Yii::app()->user->id > 0) {	
		$output .= '<div class="control-group">';
		$output .= '<label class="control-label" for="inputIcon">'. $form->labelEx($model,'slot_disabled') .'</label>';
		$output .= '<div class="controls">';
		$output .= $form->dropDownList($model,'slot_disabled',$model->getLockedOptions());
		$output .= '<span class="field-error"><strong>'.$form->error($model,'slot_disabled').'</strong></span>';
		$output .= '</div>';
		$output .= '</div>';
	} else {
		$output .= $form->hiddenField($model,'slot_disabled',array('value'=>0));
	}
	echo $output;
?>

<?php
	if ($model->isNewRecord) {
		$output = '';
		$output .= '<div class="control-group">';
		$output .= '<label class="control-label" for="inputIcon">Book Consecutive Hours</label>';
		$output .= '<div class="controls">';
		$output .= CHtml::dropDownList('block_booking', Yii::app()->request->getParam('block_booking', 1), $model->getBlockBookingValues());
		$output .= '<span class="field-error"><strong></strong></span>';
		$output .= '</div>';
		$output .= '</div>';
		echo $output;
	}
?>
	
<?php echo CHtml::htmlButton($model->isNewRecord ? '<i class="icon-ok"></i> Book Prayer Slot' : '<i class="icon-ok"></i> Save Changes', array('class'=>'btn', 'type'=>'submit')); ?>

<?php $this->endWidget(); ?>

</div><!-- form -->

protected/views/bookings/_view.php
<div class="view">

	<b><?php echo CHtml::encode($data->getAttributeLabel('id')); ?>:</b>
	<?php echo CHtml::link(CHtml::encode($data->id), array('view', 'id'=>$data->id)); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('users_name')); ?>:</b>
	<?php echo CHtml::encode($data->users_name); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('slot_booked')); ?>:</b>
	<?php echo CHtml::encode($data->slot_booked); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('slot_locked')); ?>:</b>
	<?php echo CHtml::encode($data->getLockedText()); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('slot_disabled')); ?>:</b>
	<?php echo CHtml::encode($data->getDisabledText()); ?>
	<br />
	
	<?php echo CHtml::Button('Edit', array('submit'=>'#')); ?>
	<?php 
		echo CHtml::Button(
			'Delete',
			array(
				'submit'=>Yii::app()->createUrl('bookings/delete', array('id'=>$data->id)) 
			)
		); 
	?>
	<br />

</div>

protected/views/bookings/index.php
<?php
$this->breadcrumbs=array(
	'Bookings',
);

$this->menu=array(
	array('label'=>'List Bookings','url'=>array('index'), 'active'=>true),
	//array('label'=>'Create Bookings','url'=>array('create')),
	array('label'=>'Manage Bookings','url'=>array('admin')),
);
?>

<div class="page-header">
	<h1>Bookings <small>View the complete bookings list</small></h1>
</div>

<div class="">
<?php 

/* 
 * @property string $id
 * @property string $booked_user_id
 * @property string $users_name
 * @property string $username
 * @property string $edited_user_id
 * @property string $time_created
 * @property string $time_edited
 * @property string $slot_booked
 * @property integer $slot_locked
 * @property integer $slot_disabled
 */

$this->widget('ext.bootstrap.widgets.BootGridView',array(
	'id'=>'users-grid',
	'dataProvider'=>$dataProvider,
	//'filter'=>$model,
	'columns'=>array(
		'id',
		'users_name',
		'username',
		'time_created',
		'slot_booked',
		'slot_locked',
		'slot_disabled',
		array(
			'class'=>'CLinkColumn',
            'urlExpression'=>'Yii::app()->createUrl("bookings/view", array("id"=>$data->id))',
            'label'=>'View Booking',
        ),
	),
));

?>


</div>