protected/models/User.php
<?php

/**
 * This is the model class for table "pb_user".
 *
 * The followings are the available columns in table 'pb_user':
 * @property string $id
 * @property string $username
 * @property string $password
 * @property string $name
 * @property string $last_login_time
 * @property string $create_time
 * @property string $create_user_id
 * @property string $update_time
 * @property string $update_user_id
 * @property string $system_admin
 *
 * The followings are the available model relations:
 * @property Bookings[] $bookings
 */
class User extends CActiveRecord
{
	const ADMIN_NO = 0;
	const ADMIN_YES = 1;
	
	public $password_repeat;
	
	/**
	 * Returns the static model of the specified AR class.
	 * @param string $className active record class name.
	 * @return User the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'pb_user';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('username, password, name', 'required'),
			array('username', 'email'),
			array('username, name', 'unique'),
			array('username', 'length', 'max'=>128),
			array('password, password_repeat', 'length', 'max'=>256),
			array('password_repeat', 'compare', 'compareAttribute'=>'password', 'message'=>'The password fields do not match.'),
			array('name', 'length', 'max'=>64),
			array('create_user_id, update_user_id', 'length', 'max'=>10),
			array('last_login_time, create_time, update_time, password_repeat', 'safe'),
			// The following rule is used by search().
			// Please remove those attributes that should not be searched.
			array('id, username, name, last_login_time, create_time', 'safe', 'on'=>'search'),
			// Purify
			array('username','filter','filter'=>array($obj=new CHtmlPurifier(),'purify')),
			array('password','filter','filter'=>array($obj=new CHtmlPurifier(),'purify')),
			array('name','filter','filter'=>array($obj=new CHtmlPurifier(),'purify')),
			array('password_repeat','filter','filter'=>array($obj=new CHtmlPurifier(),'purify')),
			array('create_user_id','filter','filter'=>array($obj=new CHtmlPurifier(),'purify')),
			array('update_user_id','filter','filter'=>array($obj=new CHtmlPurifier(),'purify')),
			array('last_login_time','filter','filter'=>array($obj=new CHtmlPurifier(),'purify')),
			array('create_time','filter','filter'=>array($obj=new CHtmlPurifier(),'purify')),
			array('update_time','filter','filter'=>array($obj=new CHtmlPurifier(),'purify')),
			// Strip Tags
			/*array('username','filter',function stripthosetags($value) { return strip_tags($value); }),
			array('password','filter','filter'=>function($v){ return strip_tags($v);}),
			array('name','filter','filter'=>function($v){ return strip_tags($v);}),
			array('password_repeat','filter','filter'=>function($v){ return strip_tags($v);}),
			array('create_user_id','filter','filter'=>function($v){ return strip_tags($v);}),
			array('create_time','filter','filter'=>function($v){ return strip_tags($v);}),
			array('update_user_id','filter','filter'=>function($v){ return strip_tags($v);}),
			array('last_login_time','filter','filter'=>function($v){ return strip_tags($v);}),
			array('update_time','filter','filter'=>function($v){ return strip_tags($v);}),*/
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
			'bookings' => array(self::HAS_MANY, 'Bookings', 'booked_user_id'),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'ID',
			'username' => 'Email',
			'password' => 'Password',
			'name' => 'Name',
			'last_login_time' => 'Last Login Time',
			'create_time' => 'Create Time',
			'create_user_id' => 'Create User',
			'update_time' => 'Update Time',
			'update_user_id' => 'Update User',
			'system_admin' => 'System Admin',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 * @return CActiveDataProvider the data provider that can return the models based on the search/filter conditions.
	 */
	public function search()
	{
		// Warning: Please modify the following code to remove attributes that
		// should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('id',$this->id,true);
		$criteria->compare('username',$this->username,true);
		$criteria->compare('password',$this->password,true);
		$criteria->compare('name',$this->name,true);
		$criteria->compare('last_login_time',$this->last_login_time,true);
		$criteria->compare('create_time',$this->create_time,true);
		$criteria->compare('create_user_id',$this->create_user_id,true);
		$criteria->compare('update_time',$this->update_time,true);
		$criteria->compare('update_user_id',$this->update_user_id,true);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}
	
	//*********** Custom Functions ***********//
	
	/**
	 * Prepares create_time, update_time, create_user_id, update_user_id attributes before performing validation.
	 */
	protected function beforeValidate() {
		if($this->isNewRecord) {
			// set the create date, last updated date and the user doing the creating
			$this->create_time = $this->update_time = new CDbExpression( 'NOW()' );
			$this->create_user_id = $this->update_user_id = Yii::app()->user->id;
		} else {
			//not a new record, so just set the last updated time and last updated user id
			$this->update_time = new CDbExpression( 'NOW()' );
			$this->update_user_id = Yii::app()->user->id;
       }
       return parent::beforeValidate();
	}
	
	/**
	 * perform one-way encryption on the password before we store it in the database
	 */
	protected function afterValidate() {
		parent::afterValidate();
		$this->password = $this->encrypt($this->password);
	}
     
	public function encrypt($value) {
		return md5($value);
	}
	
	//*********** Custom Functions ***********//
	
	/**
	 * @return array the admin options for the form drop down
	 */
	public function getAdminOptions() {
		return array(
			self::ADMIN_NO => 'No',
			self::ADMIN_YES => 'Yes',
		); 
	}
	
	/**
	 * @return string the admin text display for the user form view
	 */
	public function getAdminText() {
		$adminOptions=$this->adminOptions;
		return isset($adminOptions[$this->system_admin]) ?
			$adminOptions[$this->system_admin] : "unknown status ({$this->system_admin})";
	}
	
	/**
	 * @return array the of admin UID's
	 */
	public function getAdminUsers() {
		$user_records=User::model()->findAll(array(
			'select'=>'username',
			'condition'=>'system_admin=:admin',
			'params'=>array(
				':admin'=>1
			),
		));
		
		$user_array = array();
		foreach ($user_records as $key => $user_record) {
			array_push($user_array, $user_record->username);
		}
		return $user_array;
	}
	
	/**
	 * @return array the of admin UID's
	 */
	public function isAdminUser($uid = 0) {
		return User::model()->exists(array(
			'condition'=>'id =:uid AND system_admin=:admin',
			'params'=>array(
				':uid'=>$uid,
				':admin'=>1,
			),
		));
	}
}

protected/controllers/UserController.php
<?php

class UserController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		$userModel=new User;
		
		return array(
			array(
				'allow',  // allow all users to perform 'index' and 'view' actions
                'actions'=>array('create'),
                'users'=>array('*'),
			),
			array(
				'allow',  // allow all users to perform 'index' and 'view' actions
                'actions'=>array('update'),
                'users'=>array('@'),
			),
			array(
				'allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('index','view','admin','delete'),
            	'users'=>$userModel->getAdminUsers(),
        	),
			array(
				'deny',  // deny all users
            	'users'=>array('*'),
			), 
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new User;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['User']))
		{
			$model->attributes=$_POST['User'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['User']))
		{
			$model->attributes=$_POST['User'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		if(Yii::app()->request->isPostRequest)
		{
			// we only allow deletion via POST request
			$this->loadModel($id)->delete();

			// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
			if(!isset($_GET['ajax']))
				$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
		}
		else
			throw new CHttpException(400,'Invalid request. Please do not repeat this request again.');
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('User');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new User('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['User']))
			$model->attributes=$_GET['User'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer the ID of the model to be loaded
	 */
	public function loadModel($id)
	{
		$model=User::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param CModel the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='user-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

protected/views/user/_form.php
<?php /** @var BootActiveForm $form */
$form = $this->beginWidget('bootstrap.widgets.BootActiveForm', array(
    'id'=>'users-form',
    'type'=>'inline',
    'enableClientValidation'=>true,
    'clientOptions'=>array(
		'validateOnSubmit'=>true,
	),
    'htmlOptions'=>array('class'=>'well'),
));

$userModel = new User;
?>
	<p class="help-block">Fields with <span class="required">*</span> are required.</p>

	<?php echo $form->errorSummary($model); ?>
	
	<?php 
		$output = '';
		$output .= '<div class="control-group">';
		$output .= '<label class="control-label" for="inputIcon">'. $form->labelEx($model,'username') .'</label>';
		$output .= '<div class="controls">';
		$output .= $form->textFieldRow($model, 'username', array('class'=>'span5','maxlength'=>128));
		$output .= '<span class="field-error"><strong>'.$form->error($model,'username').'</strong></span>';
		$output .= '</div>';
		$output .= '</div>';
		echo $output;
	?>

	
	<?php 
		$output = '';
		$output .= '<div class="control-group">';
		$output .= '<label class="control-label" for="inputIcon">'. $form->labelEx($model,'name') .'</label>';
		$output .= '<div class="controls">';
		$output .= $form->textFieldRow($model, 'name', array('class'=>'span5','maxlength'=>64));
		$output .= '<span class="field-error"><strong>'.$form->error($model,'name').'</strong></span>';
		$output .= '</div>';
		$output .= '</div>';
		echo $output;
	?>
	
	<?php 
		$output = '';
		$output .= '<div class="control-group">';
		$output .= '<label class="control-label" for="inputIcon">'. $form->labelEx($model,'password') .'</label>';
		$output .= '<div class="controls">';
		$output .= $form->textFieldRow($model, 'password', array('class'=>'span5','maxlength'=>64, 'value'=>''));
		$output .= '<span class="field-error"><strong>'.$form->error($model,'password').'</strong></span>';
		$output .= '</div>';
		$output .= '</div>';
		echo $output;
	?>

	
	<?php 
		$output = '';
		$output .= '<div class="control-group">';
		$output .= '<label class="control-label" for="inputIcon">'. $form->labelEx($model,'password_repeat') .'</label>';
		$output .= '<div class="controls">';
		$output .= $form->textFieldRow($model, 'password_repeat', array('class'=>'span5','maxlength'=>64, 'value'=>''));
		$output .= '<span class="field-error"><strong>'.$form->error($model,'password_repeat').'</strong></span>';
		$output .= '</div>';
		$output .= '</div>';
		echo $output;
	?>
	
	<?php
		if ($userModel->isAdminUser(Yii::app()->user->id)) {
			$output = '';	
			$output .= '<div class="control-group">';
			$output .= '<label class="control-label" for="inputIcon">'. $form->labelEx($model,'system_admin') .'</label>';
			$output .= '<div class="controls">';
			$output .= $form->dropDownList($model,'system_admin',$model->getAdminOptions());
			$output .= '<span class="field-error"><strong>'.$form->error($model,'system_admin').'</strong></span>';
			$output .= '</div>';
			$output .= '</div>';
			echo $output;
		}
	?>
	
	<?php echo CHtml::htmlButton('<i class="icon-ok"></i>'.$model->isNewRecord ? ' Create' : ' Save', array('class'=>'btn', 'type'=>'submit')); ?>

<?php $this->endWidget(); ?>

protected/views/user/_search.php
<div class="wide form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

	<div class="row">
		<?php echo $form->label($model,'id'); ?>
		<?php echo $form->textField($model,'id',array('size'=>10,'maxlength'=>10)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'username'); ?>
		<?php echo $form->textField($model,'username',array('size'=>60,'maxlength'=>128)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'name'); ?>
		<?php echo $form->textField($model,'name',array('size'=>60,'maxlength'=>64)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'last_login_time'); ?>
		<?php echo $form->textField($model,'last_login_time'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'create_time'); ?>
		<?php echo $form->textField($model,'create_time'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'create_user_id'); ?>
		<?php echo $form->textField($model,'create_user_id',array('size'=>10,'maxlength'=>10)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'update_time'); ?>
		<?php echo $form->textField($model,'update_time'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'update_user_id'); ?>
		<?php echo $form->textField($model,'update_user_id',array('size'=>10,'maxlength'=>10)); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton('Search'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- search-form -->

protected/views/user/_view.php
<div class="view">

	<b><?php echo CHtml::encode($data->getAttributeLabel('id')); ?>:</b>

	<?php echo CHtml::link(CHtml::encode($data->id),array('view','id'=>$data->id)); ?>
	<br />
	
	<b><?php echo CHtml::encode($data->getAttributeLabel('username')); ?>:</b>
	<?php echo CHtml::encode($data->username); ?>
	<br />
	
	<b><?php echo CHtml::encode($data->getAttributeLabel('name')); ?>:</b>
	<?php echo CHtml::encode($data->name); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('create_time')); ?>:</b>
	<?php echo CHtml::encode($data->create_time); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('last_login_time')); ?>:</b>
	<?php echo CHtml::encode($data->last_login_time); ?>
	<br />
	
	
	<b><?php echo CHtml::encode($data->getAttributeLabel('update_time')); ?>:</b>
	<?php echo CHtml::encode($data->update_time); ?>
	<br />
	
	
</div>

protected/views/user/admin.php
<?php
$this->breadcrumbs=array(
	'Users'=>array('index'),
	'Manage',
);

$this->menu=array(
	array('label'=>'Manage Users','url'=>array('admin'), 'active'=>true),
	array('label'=>'List Users','url'=>array('index')),
	array('label'=>'Create Users','url'=>array('create')),
);

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});

$('.search-form form').submit(function(){
	$.fn.yiiGridView.update('users-grid', {
		data: $(this).serialize()
	});
	return false;
});");
?>

<div class="page-header">
	<h1>Manage Users <small>Use this tool to manage the system's users</small></h1>
</div>

<div class="alert alert-info">
	<a class="close" data-dismiss="alert">×</a>
	<strong>Search Instructions</strong> You may optionally enter a comparison operator (<b>&lt;</b>, <b>&lt;=</b>, <b>&gt;</b>, <b>&gt;=</b>, <b>&lt;&gt;</b>
or <b>=</b>) at the beginning of each of your search values to specify how the comparison should be done.'
</div>

<?php echo CHtml::link('Advanced Search','#',array('class'=>'search-button btn')); ?>

<div class="search-form well" style="display:none">

<?php $this->renderPartial('_search',array(

	'model'=>$model,

)); ?>
</div><!-- search-form -->

<?php
/*
 * @property string $id
 * @property string $username
 * @property string $password
 * @property string $name
 * @property string $last_login_time
 * @property string $create_time
 * @property string $create_user_id
 * @property string $update_time
 * @property string $update_user_id
 * @property string $system_admin
 */
?>
<?php $this->widget('ext.bootstrap.widgets.BootGridView',array(

	'id'=>'users-grid',
	'dataProvider'=>$model->search(),
	//'filter'=>$model,
	'columns'=>array(
		'id',
		'name',
		'username',
		'create_time',
		'last_login_time',
		'update_time',
		'system_admin',
		array(
			'class'=>'CButtonColumn',
		),

	),

)); ?>

protected/views/user/create.php
<?php
$this->breadcrumbs=array(
	'Users'=>array('index'),
	'Create',
);

$this->menu=array(
array('label'=>'Create Users','url'=>array('create'), 'active'=>true),
	array('label'=>'List Users','url'=>array('index')),
	array('label'=>'Manage Users','url'=>array('admin')),
);
?>

<div class="page-header">
	<h1>Create Users <small>Add a user to your database</small></h1>
</div>

<div class="">
<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>
</div>

protected/views/user/index.php
<?php
$this->breadcrumbs=array(
	'Users',
);

$this->menu=array(
	array('label'=>'List Users','url'=>array('index'), 'active'=>true),
	array('label'=>'Create Users','url'=>array('create')),
	array('label'=>'Manage Users','url'=>array('admin')),
);
?>

<div class="page-header">
	<h1>Users <small>View the complete user list</small></h1>
</div>

<div class="">
<?php 

$this->widget('ext.bootstrap.widgets.BootGridView',array(
	'id'=>'users-grid',
	'dataProvider'=>$dataProvider,
	//'filter'=>$model,
	'columns'=>array(
		'id',
		'username',
		'name',
		'create_time',
		'last_login_time',
		'update_time',
		'system_admin',
		array(
			'class'=>'CLinkColumn',
            'urlExpression'=>'Yii::app()->createUrl("user/view", array("id"=>$data->id))',
            'label'=>'View User',
        ),
	),
));

?>


</div>

protected/views/user/update.php
<?php
$userModel = new User;

if ($userModel->isAdminUser(Yii::app()->user->id)) {
	$this->breadcrumbs=array(
		'Users'=>array('index'),
		$model->id=>array('view','id'=>$model->id),
		'Update',
	);

	$this->menu=array(
		array('label'=>'Update User #'.$model->id,'url'=>array('update','id'=>$model->id),'active'=>true),
		array('label'=>'List Users','url'=>array('index')),
		array('label'=>'Create Users','url'=>array('create')),
		array('label'=>'View Users','url'=>array('view','id'=>$model->id)),
		array('label'=>'Manage Users','url'=>array('admin')),
	);
} else if (Yii::app()->user->id != $model->id) throw new CHttpException(400,'Invalid request. Please do not repeat this request again. This action has been reported!')
?>

<div class="page-header">
	<h1>Update User #<?php echo $model->id; ?> <small>Make changes here</small></h1>
</div>

<div class="">
<?php echo $this->renderPartial('_form',array('model'=>$model)); ?>
</div>

protected/views/user/view.php
<?php
$this->breadcrumbs=array(
	'Users'=>array('index'),
	$model->id,
);

$this->menu=array(
	array('label'=>'View User #'.$model->id,'url'=>array('view','id'=>$model->id),'active'=>true),
	array('label'=>'List Users','url'=>array('index')),
	array('label'=>'Create Users','url'=>array('create')),
	array('label'=>'Update Users','url'=>array('update','id'=>$model->id)),
	array('label'=>'Delete User','url'=>'#','linkOptions'=>array('submit'=>array('delete','id'=>$model->id),'confirm'=>'Are you sure you want to delete this item?')),
	array('label'=>'Manage Users','url'=>array('admin')),
);
?>

<div class="page-header">
	<h1>View User #<?php echo $model->id; ?> <small>Details for user <?php echo $model->id; ?></small></h1>
</div>

<?php $this->widget('ext.bootstrap.widgets.BootDetailView',array(
	'data'=>$model,
	'attributes'=>array(
		'id',
		'username',
		'name',
		'last_login_time',
		'create_time',
		'update_time',
		'system_admin',
	),
)); ?>